### PR TITLE
Add documentation to ReadTheDocs

### LINKED ISSUE #111: Switch to readthedocs
README.rst is starting to become unwieldy.  It would be nice if we had proper Sphinx documentation on our objects.

### PR DESCRIPTION
**Pull request by KeyWeeUsr**
Copies README.rst + adds basic structure + `automodule` for each module except `xpath` (seems like a file with constants only).

Documentation is here: https://pykeepass.readthedocs.io/en/latest/, currently built from my `rtd` branch. Create accounts on RTD so I can give you maintainer access. :yum: 

Closes #111

### CODE REVIEW

**Comment by pschmitt** [comment]
Sweet!

**Comment by KeyWeeUsr** [comment]
I've given access to @Evidlo on RTD, still missing you @pschmitt. Is there anything else I can change to have this PR merged?

**Comment by pschmitt** [comment]
I'm pschmitt on rtd as well.
Other than that this lgtm.

**Comment by KeyWeeUsr** [comment]
@pschmitt access added :+1:

**Comment by pschmitt** [comment]
If you don't have any objection I'll merge this one @Evidlo

**Comment by pschmitt** [comment]
Merging..!
Thanks a lot @KeyWeeUsr 
I will be updating the repo the RTD points to.

**Pull request merged**
