### PR TITLE
entry: move entries within a group

### PR DESCRIPTION
**Pull request by pwall2222**
Code changes:
- Add `index` property to Entry
- Add `move` method to Entry
- Add `_first_entry` property to Group

Explanation:
To move Entries around we need to remove and then insert at the desired index, the KDBX format makes it so that Entries and group info is all mixed, so we have to get the first element index to position correctly the Entries.

If you know a better method to get the index of the first entry I'll put it in.

What it does:

It moves entries around a group, pretty self explanatory, like the Keepass and KeepassXC functionality.

### CODE REVIEW

**Comment by pwall2222** [comment]
Is just for feature parity with the `KeePassXC` client.

**Comment by Evidlo** [comment]
Perhaps it would be better to call this `.reindex()` or something similar.  I'd like to avoid confusion with the `move_entry()` function, which is for hierarchical operations.

**Comment by pwall2222** [comment]
As you sugggested I added a test and I rename the function to `reindex`.
The keepassxc custom reorder, but anyway it was a feature in the original keepass.
https://github.com/keepassxreboot/keepassxc/issues/2295
https://github.com/keepassxreboot/keepassxc/pull/4357

**Comment by Evidlo** [comment]
Thanks!  This looks good so far.

Would you mind adding [docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) on `reindex` and `index` and also in README.md beneath `move_entry`?  Sorry, I should've mentioned that before.  After that it looks good to merge.

**Comment by pwall2222** [comment]
Shouldn't it be near `Entry.delete_attachment` since its in the `Entry` class it self?

**Comment by Evidlo** [comment]
> Shouldn't it be near Entry.delete_attachment since its in the Entry class it self?

Actually there doesn't appear to be sections for Group/Entry member functions in the README, so you can ignore that for now.

**Pull request merged**
