### PR TITLE
Fix <= version (4,0) ~version 3 add_binary ID referencing

### PR DESCRIPTION
**Pull request by disarticulate**
I inspected a kdbx created by KeePass, and found that /KeePassFile/Meta/Binaries/Binary requires an ID key to reference the proper data, and fixed a `data = base64.b64encode(data).decode` typo which was not decoding the data.

See https://github.com/pschmitt/pykeepass/issues/146#issue-421943414 for debug details

### CODE REVIEW

**Comment by Evidlo** [comment]
Please wait until https://github.com/disarticulate/pykeepass/pull/1 is merged before merging this.

**Comment by lmussier** [comment]
Hi,

Any update  / ETA on this PR.
We are facing the exact same issue  :s

**Comment by sergiofagostinho** [comment]
Also looking forward for this, as we suspect this will address #143.

**Comment by Venti-** [comment]
I tried this patch, specifically https://github.com/disarticulate/pykeepass/commit/e6f73e7623f5cd7b3f157a70f06e4f27f5024dec, and found that this fixes some of the issue, but weirdness remains.

- After adding an attachment, PyKeePass.attachments is None, and the attachment is only seen in binaries.
- With a kdbx3.1 file, I could not open the attachment with Strongbox or MacPass. In StrongBox I could see the attachment, but the content was not decrypted correctly. In MacPass I could not see the attachment at all. PyKeePass could read the attachment.
- With a kdbx4.0 file, saving the attachment seemed to work correctly.

I don't know enough about KeePass file format to figure out what's wrong exactly, but here is the code to reproduce the problem.

```python
kp = PyKeePass(KP_PATH, password=password)

# Setup one group named test_group without any entries.
while len(kp.binaries) > 0:
    kp.delete_binary(0)
group = kp.find_groups(path='test_group', first=True)
if group is None:
    group = kp.add_group(kp.root_group, 'test_group')
entry = kp.find_entries(group=group, title='test_title', first=True)
if entry is not None:
    kp.delete_entry(entry)

print('# attachments', kp.attachments)
print('# binaries', kp.binaries)

entry = kp.add_entry(kp.root_group, title='test_title', username='', password='')
attachment_id = kp.add_binary(b'test bytes')
entry.add_attachment(attachment_id, 'test_filename')

print("# entry.attachments =", entry.attachments)
attachment = entry.attachments[0]
print("# attachment.id='{id}', attachment.filename='{filename}', attachment.data='{data}'".format(
    id=attachment.id, filename=attachment.filename, data=attachment.data))

print('# attachments', kp.attachments)
print('# binaries', kp.binaries)

kp.save()
```
```
# version (3, 1)
# kdf_algorithm aeskdf
# binaries [b'test bytes']
# kp.delete_binary(0)
# attachments None
# binaries []
# entry.attachments = [Attachment: 'test_filename' -> 0]
# attachment.id='0', attachment.filename='test_filename', attachment.data='b'test bytes''
# attachments None
# binaries [b'test bytes']
```

**Comment by Evidlo** [comment]
Don't merge this until https://github.com/disarticulate/pykeepass/pull/2 is merged

**Comment by Evidlo** [comment]
@disarticulate Could you merge https://github.com/disarticulate/pykeepass/pull/2

**Comment by disarticulate** [comment]
oops. sorry guys, i thought we merged em together.

**Comment by Garcia6l20** [comment]
@disarticulate Maybe you could re-open ?

**Comment by Garcia6l20** [comment]
@disarticulate I might have warned you, I already had same issue. Try [this](https://github.com/pschmitt/pykeepass/pull/166/files).

**Comment by Evidlo** [comment]
@disarticulate Why again are we doing `.decode()` after `b64decode`?  Shouldn't the result be a bytestring, not a regular string, since these are binaries?

**Comment by disarticulate** [comment]
All I knew was decode is a function which doesn't make sense in the context.

It could have been it's own merge request.

**Pull request merged**
