### PR TITLE
Fix char filtering to work with narrow python

### PR DESCRIPTION
**Pull request by Evidlo**
Continuation from https://github.com/libkeepass/pykeepass/pull/209

### CODE REVIEW

**Comment by Evidlo** [comment]
The alternative Unicode stripping method seems to be pretty slow, probably because we are iterating every character in the XML.  I added a commit which only falls back to this method if we are on a narrow build.

Can you confirm that the tests pass on your narrow 2.7 build on Windows?

**Comment by Evidlo** [comment]
@MoisMoshev bump

**Comment by MoisMoshev** [comment]
Hey, I can confirm that the tests pass on Python 2.7. As already said though, since 2.7 is past EOL, I do not insist on this being merged.

**Comment by Evidlo** [comment]
We've sinced dropped Python 2 support, so I'm closing this.

**Comment by MoisMoshev** [comment]
Yay, we are finally done with Py 2!

**Pull request closed without merging**
